### ISSUE TITLE
trial_generator fails due to "field type must be `float`"

### ISSUE THREAD

**Issue by endre90** [usnistgov/ARIAC#306]
#### OS:
Ubuntu 22.04
#### ROS2:
Humble (binaries)
#### Issue:
```
ros2 run ariac_gui trial_generator
started_node
Traceback (most recent call last):
  File "~/ariac_ws/install/ariac_gui/lib/ariac_gui/trial_generator", line 33, in <module>
    sys.exit(load_entry_point('ariac-gui==2024.1.0', 'console_scripts', 'trial_generator')())
  File "~/ariac_ws/install/ariac_gui/lib/python3.10/site-packages/ariac_gui/trial_generator_node.py", line 23, in main
    main_gui = GUI_CLASS()
  File "~/ariac_ws/install/ariac_gui/lib/python3.10/site-packages/ariac_gui/trial_generator.py", line 420, in __init__
    self._build_assembly_parts_pose_direction()
  File "~/ariac_ws/install/ariac_gui/lib/python3.10/site-packages/ariac_gui/trial_generator.py", line 540, in _build_assembly_parts_pose_direction
    regulator_install_direction.x = 0
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/geometry_msgs/msg/_vector3.py", line 135, in x
    assert \
AssertionError: The 'x' field must be of type 'float'
[ros2run]: Process exited with failure 1
```
#### Fix that worked for me:
Specify `float` type in `trial_generator.py`.
Lines 540-542:
```
regulator_install_direction.x = 0  -> regulator_install_direction.x = 0.0
regulator_install_direction.y = 0  -> regulator_install_direction.y = 0.0
regulator_install_direction.z = -1 -> regulator_install_direction.z = -1.0
```
Do the same for lines 551-553, 562-564, and 573-575.

**Comment by jaybrecht** [comment]
Hello, as Issac mentioned on #305, the supported ROS version for ARIAC 2024 is Iron. We just verified that this bug is only present when running the trial generator on humble.

**Comment by endre90** [comment]
Thanks, I'll switch to Iron
