### ISSUE TITLE
error when running with github release

### ISSUE THREAD

**Issue by dan9thsense** [usnistgov/ARIAC#341]
I created a release version of the github repository and it builds ok with build_container.sh but in run_trial.sh, the sim environment crashes with the error below. Looking in the container, /workspace/src/ARIAC/ariac_log/README.md exists, but, of course, is just a file, while the code seems to be expecting a directory there.

```
An instance of Gazebo is not running.
Gazebo not running
Traceback (most recent call last):
  File "/container_scripts/run_trial.py", line 106, in <module>
    main()
  File "/container_scripts/run_trial.py", line 90, in main
    shutil.copy(
  File "/usr/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
NotADirectoryError: [Errno 20] Not a directory: '/workspace/src/ARIAC/ariac_log/README.md/sensor_cost.txt'
```

**Comment by dan9thsense** [comment]
Nevermind, local issue-- fixed
